### PR TITLE
Update wsk.rb

### PR DESCRIPTION
**Pull request by ssx**
Fix for newer homebrew.

### CODE REVIEW

**Comment by shaftoe** [comment]
Sorry @ssx for the late, I must have missed this. Are you still interested in fixing / taking over?

**Comment by ssx** [comment]
Hi Alex,

Sure!

**Comment by shaftoe** [comment]
I'd suggest to just update the README and make it just a pointer to your project, I've got not interest anymore in maintaining this (as you might have already understood...)

**Comment by ssx** [comment]
PR sent :)

**Pull request closed without merging**
